/**
 * DAA Document Generator - ENHANCED VERSION (Jan 2026)
 * 
 * Generates comprehensive Debt Acknowledgment Agreements matching
 * the detailed template structure with:
 * - Complete legal framework with academic citations
 * - Detailed exhibits (A-E) with primary sources
 * - Per-person debt calculations
 * - FamilySearch ARK links
 * - TODO placeholders for future improvements
 * 
 * Based on Danyela Brown's comprehensive DAA template
 * Uses the 'docx' library for professional document generation
 * 
 * ENHANCEMENT NOTES (Jan 31, 2026):
 * - Copied legal framework verbatim from template
 * - Added detailed calculation methodology (Exhibit B)
 * - Added per-person inheritance accounting (Exhibit D)
 * - TODO: Verify all academic citations with legal research team
 * - TODO: Enhance birth year estimation logic
 * - TODO: Add multi-generation ownership chain calculations
 */

const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, Table, TableRow, TableCell, WidthType, BorderStyle } = require('docx');
const fs = require('fs');
const path = require('path');

class DAADocumentGenerator {
    constructor() {
        this.outputDir = path.join(__dirname, '../../../generated-daas');
        
        // Ensure output directory exists
        if (!fs.existsSync(this.outputDir)) {
            fs.mkdirSync(this.outputDir, { recursive: true });
        }
        
        // TODO [JAN 2026]: Base calculation from template - verify with economic research
        // Current placeholder uses simplified formula from database
        this.BASE_DAILY_WAGE = 120; // $120/day from template
        this.WORKING_DAYS_PER_YEAR = 300;
        this.INFLATION_MULTIPLIER = 30; // 1860→2025
        this.COMPOUND_INTEREST_RATE = 0.04; // 4% annual
        this.DELAYED_JUSTICE_MULTIPLIER = 3.2; // 2% × 160 years
    }

    /**
     * Generate comprehensive DAA DOCX document
     */
    async generateDOCX(daaRecord, slaveholderData, debtCalculation, acknowledgerInfo) {
        const sections = [];

        // Title Page
        sections.push(
            ...this.createTitlePage(acknowledgerInfo, daaRecord)
        );

        // Table of Contents (placeholder)
        sections.push(
            new Paragraph({
                text: 'TABLE OF CONTENTS',
                heading: HeadingLevel.HEADING_1,
                alignment: AlignmentType.CENTER,
                spacing: { before: 400, after: 200 }
            }),
            new Paragraph({
                text: '[Table of Contents will be generated by Word]',
                alignment: AlignmentType.CENTER,
                spacing: { after: 400 }
            }),
            this.createPageBreak()
        );

        // Part I: Legal Framework
        sections.push(
            ...this.createLegalFramework(daaRecord, slaveholderData, debtCalculation)
        );

        // Article I: Acknowledgment of Debt
        sections.push(
            ...this.createDebtAcknowledgment(daaRecord, slaveholderData, debtCalculation)
        );

        // Article II: Payment Terms
        sections.push(
            ...this.createPaymentTerms(daaRecord, acknowledgerInfo)
        );

        // Article III: Escrow and Disbursement
        sections.push(
            ...this.createEscrowTerms()
        );

        // Article IV: Legal Effect and Waivers
        sections.push(
            ...this.createLegalWaivers()
        );

        // Article V: Annual Re-Petition
        sections.push(
            ...this.createPetitionTerms()
        );

        // Exhibits: Primary Sources
        sections.push(
            ...this.createExhibits(slaveholderData)
        );

        // Signature Page
        sections.push(
            ...this.createSignaturePage(acknowledgerInfo, daaRecord)
        );

        // Create document
        const doc = new Document({
            sections: [{
                properties: {},
                children: sections
            }]
        });

        // Generate filename
        const filename = `DAA-${daaRecord.agreementNumber}-${acknowledgerInfo.name.replace(/\s+/g, '_')}.docx`;
        const filepath = path.join(this.outputDir, filename);

        // Write to file
        const buffer = await Packer.toBuffer(doc);
        fs.writeFileSync(filepath, buffer);

        return filepath;
    }

    /**
     * Create title page
     */
    createTitlePage(acknowledgerInfo, daaRecord) {
        return [
            new Paragraph({
                text: 'DEBT ACKNOWLEDGMENT AGREEMENT',
                heading: HeadingLevel.TITLE,
                alignment: AlignmentType.CENTER,
                spacing: { before: 400, after: 200 }
            }),
            new Paragraph({
                text: 'With Primary Source Documentation',
                alignment: AlignmentType.CENTER,
                spacing: { after: 400 }
            }),
            new Paragraph({
                text: '─'.repeat(60),
                alignment: AlignmentType.CENTER,
                spacing: { after: 200 }
            }),
            new Paragraph({
                text: 'In the Matter of:',
                alignment: AlignmentType.CENTER,
                spacing: { after: 100 }
            }),
            new Paragraph({
                text: acknowledgerInfo.name.toUpperCase(),
                alignment: AlignmentType.CENTER,
                bold: true,
                spacing: { after: 100 }
            }),
            new Paragraph({
                text: 'Obligor',
                alignment: AlignmentType.CENTER,
                spacing: { after: 200 }
            }),
            new Paragraph({
                text: `Document No. ${daaRecord.agreementNumber}`,
                alignment: AlignmentType.CENTER,
                spacing: { after: 100 }
            }),
            new Paragraph({
                text: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
                alignment: AlignmentType.CENTER,
                spacing: { after: 400 }
            }),
            this.createPageBreak()
        ];
    }

    /**
     * Create legal framework section
     */
    createLegalFramework(daaRecord, slaveholderData, debtCalculation) {
        const sections = [
            new Paragraph({
                text: 'PART I: LEGAL FRAMEWORK',
                heading: HeadingLevel.HEADING_1,
                spacing: { before: 400, after: 200 }
            }),
            new Paragraph({
                text: 'This Debt Acknowledgment Agreement ("Agreement" or "DAA") is entered into as of ' +
                      new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }) +
                      ', by the undersigned Obligor, acting voluntarily and with full knowledge of the moral and legal implications hereof.',
                spacing: { after: 200 }
            }),
            new Paragraph({
                text: 'PARTIES',
                heading: HeadingLevel.HEADING_2,
                spacing: { before: 300, after: 100 }
            }),
            new Paragraph({
                text: `OBLIGOR: ${daaRecord.acknowledger_name}, a natural person and documented descendant of slaveholders, acknowledging inherited debt arising from the forced labor of enslaved persons.`,
                spacing: { after: 100 }
            }),
            new Paragraph({
                text: `BENEFICIARY CLASS: The documented descendants of the ${debtCalculation.totalEnslavedCount} enslaved persons named herein, and their heirs and assigns, collectively and severally.`,
                spacing: { after: 200 }
            })
        ];

        // Add RECITALS for each slaveholder
        sections.push(
            new Paragraph({
                text: 'RECITALS',
                heading: HeadingLevel.HEADING_2,
                spacing: { before: 300, after: 100 }
            }),
            new Paragraph({
                text: 'WHEREAS:',
                spacing: { after: 100 }
            })
        );

        // Add recital for each slaveholder
        let recitalLetter = 'A';
        for (const data of slaveholderData) {
            const sh = data.slaveholder;
            const sources = data.primarySources;
            
            sections.push(
                new Paragraph({
                    text: `${recitalLetter}. ${sh.slaveholder_name} (${sh.slaveholder_birth_year || 'dates unknown'}), a slaveholder documented in ${sh.primary_state || 'historical records'}, did hold in bondage ${data.enslavedPersons.length} individual(s) as recorded in primary source documentation including ${sources[0]?.document_type || 'historical documents'} accessible via FamilySearch ARK ${sources[0]?.ark || 'TBD'}.`,
                    spacing: { after: 100 }
                })
            );
            
            recitalLetter = String.fromCharCode(recitalLetter.charCodeAt(0) + 1);
        }

        // Add standard recitals
        sections.push(
            new Paragraph({
                text: `${recitalLetter}. Recent economic research has conclusively demonstrated that descendants of slaveholders recovered their wealth within one generation following the Civil War through strategic marriages and social networks, and that this wealth remains traceable through documented family networks. (Ager, Boustan & Eriksson, "The Intergenerational Effects of a Large Wealth Shock," American Economic Review 2021)`,
                spacing: { after: 100 }
            })
        );

        return sections;
    }

    /**
     * Create debt acknowledgment section
     */
    createDebtAcknowledgment(daaRecord, slaveholderData, debtCalculation) {
        const sections = [
            this.createPageBreak(),
            new Paragraph({
                text: 'ARTICLE I: ACKNOWLEDGMENT OF DEBT',
                heading: HeadingLevel.HEADING_1,
                spacing: { before: 400, after: 200 }
            }),
            new Paragraph({
                text: 'Section 1.1 — Principal Acknowledgment',
                heading: HeadingLevel.HEADING_2,
                spacing: { before: 200, after: 100 }
            }),
            new Paragraph({
                text: `Obligor hereby acknowledges and affirms that Obligor has inherited, through the mechanisms of intergenerational wealth transfer, social capital, and network advantages, a debt obligation arising from the unpaid labor of the ${debtCalculation.totalEnslavedCount} enslaved persons documented herein.`,
                spacing: { after: 200 }
            }),
            new Paragraph({
                text: 'Section 1.2 — Calculation of Debt',
                heading: HeadingLevel.HEADING_2,
                spacing: { before: 200, after: 100 }
            }),
            new Paragraph({
                text: 'The total debt has been calculated using the methodology set forth in Exhibit B, incorporating:',
                spacing: { after: 100 }
            }),
            new Paragraph({
                text: '(a) Base Daily Wage: $1.00 per day × 300 working days per year;',
                spacing: { after: 50 }
            }),
            new Paragraph({
                text: '(b) Compound Interest: 3% annual rate from year of enslavement to 2025;',
                spacing: { after: 50 }
            }),
            new Paragraph({
                text: '(c) Wealth Multiplier: 2.5x (Ager, Boustan & Eriksson, AER 2021);',
                spacing: { after: 50 }
            }),
            new Paragraph({
                text: '(d) Inflation Adjustment: 5.1x (1860→2025).',
                spacing: { after: 200 }
            })
        ];

        // Add debt breakdown table per slaveholder
        sections.push(
            new Paragraph({
                text: 'As documented in the attached exhibits, the combined debt is calculated as follows:',
                spacing: { after: 100 }
            })
        );

        // Create table
        const tableRows = [
            new TableRow({
                children: [
                    new TableCell({ children: [new Paragraph({ text: 'Slaveholder', bold: true })] }),
                    new TableCell({ children: [new Paragraph({ text: 'Enslaved Persons', bold: true })] }),
                    new TableCell({ children: [new Paragraph({ text: 'Subtotal Debt', bold: true })] })
                ]
            })
        ];

        for (const calc of debtCalculation.slaveholderCalculations) {
            tableRows.push(
                new TableRow({
                    children: [
                        new TableCell({ children: [new Paragraph(calc.slaveholder.slaveholder_name)] }),
                        new TableCell({ children: [new Paragraph(calc.enslavedCount.toString())] }),
                        new TableCell({ children: [new Paragraph(`$${calc.debt.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`)] })
                    ]
                })
            );
        }

        // Total row
        tableRows.push(
            new TableRow({
                children: [
                    new TableCell({ children: [new Paragraph({ text: 'TOTAL', bold: true })] }),
                    new TableCell({ children: [new Paragraph({ text: debtCalculation.totalEnslavedCount.toString(), bold: true })] }),
                    new TableCell({ children: [new Paragraph({ text: `$${debtCalculation.totalDebt.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, bold: true })] })
                ]
            })
        );

        sections.push(
            new Table({
                width: { size: 100, type: WidthType.PERCENTAGE },
                rows: tableRows
            })
        );

        return sections;
    }

    /**
     * Create payment terms section
     */
    createPaymentTerms(daaRecord, acknowledgerInfo) {
        return [
            this.createPageBreak(),
            new Paragraph({
                text: 'ARTICLE II: PAYMENT TERMS',
                heading: HeadingLevel.HEADING_1,
                spacing: { before: 400, after: 200 }
            }),
            new Paragraph({
                text: 'Section 2.1 — Payment Obligation',
                heading: HeadingLevel.HEADING_2,
                spacing: { before: 200, after: 100 }
            }),
            new Paragraph({
                text: 'Obligor agrees to pay Two Percent (2%) of Obligor\'s gross annual income, payable in equal monthly installments, toward satisfaction of the debt acknowledged herein.',
                spacing: { after: 200 }
            }),
            new Paragraph({
                text: 'Section 2.2 — Current Payment Calculation',
                heading: HeadingLevel.HEADING_2,
                spacing: { before: 200, after: 100 }
            }),
            new Paragraph({
                text: `Based on Obligor's current gross annual income of $${acknowledgerInfo.annualIncome.toLocaleString()}, the initial annual payment shall be $${daaRecord.annualPayment.toLocaleString()} (approximately $${(daaRecord.annualPayment / 12).toFixed(2)} per month).`,
                spacing: { after: 200 }
            }),
            new Paragraph({
                text: 'Section 2.3 — Duration',
                heading: HeadingLevel.HEADING_2,
                spacing: { before: 200, after: 100 }
            }),
            new Paragraph({
                text: 'Payment obligations shall continue until the earlier of:',
                spacing: { after: 50 }
            }),
            new Paragraph({
                text: '(a) The enactment of federal reparations legislation (including but not limited to HR 40 or equivalent);',
                spacing: { after: 50 }
            }),
            new Paragraph({
                text: '(b) Thirty (30) years from the date of execution; or',
                spacing: { after: 50 }
            }),
            new Paragraph({
                text: '(c) The death of Obligor, at which time any remaining obligation shall transfer to Obligor\'s estate.',
                spacing: { after: 200 }
            })
        ];
    }

    /**
     * Create escrow terms section
     */
    createEscrowTerms() {
        return [
            this.createPageBreak(),
            new Paragraph({
                text: 'ARTICLE III: ESCROW AND DISBURSEMENT',
                heading: HeadingLevel.HEADING_1,
                spacing: { before: 400, after: 200 }
            }),
            new Paragraph({
                text: 'Section 3.1 — Blockchain Escrow',
                heading: HeadingLevel.HEADING_2,
                spacing: { before: 200, after: 100 }
            }),
            new Paragraph({
                text: 'All payments shall be deposited into a blockchain-anchored escrow account with transparent and auditable transaction history.',
                spacing: { after: 200 }
            })
        ];
    }

    /**
     * Create legal waivers section
     */
    createLegalWaivers() {
        return [
            this.createPageBreak(),
            new Paragraph({
                text: 'ARTICLE IV: LEGAL EFFECT AND WAIVERS',
                heading: HeadingLevel.HEADING_1,
                spacing: { before: 400, after: 200 }
            }),
            new Paragraph({
                text: 'Section 4.1 — Voluntary Waiver of Defenses',
                heading: HeadingLevel.HEADING_2,
                spacing: { before: 200, after: 100 }
            }),
            new Paragraph({
                text: 'Obligor voluntarily waives the following defenses:',
                spacing: { after: 50 }
            }),
            new Paragraph({
                text: '(a) Statute of Limitations: This is a current, voluntary assumption of obligation;',
                spacing: { after: 50 }
            }),
            new Paragraph({
                text: '(b) Standing: Obligor affirms direct connection through documented genealogical inheritance;',
                spacing: { after: 50 }
            }),
            new Paragraph({
                text: '(c) Attenuation: Obligor acknowledges the documented chain of wealth transmission.',
                spacing: { after: 200 }
            })
        ];
    }

    /**
     * Create petition terms section
     */
    createPetitionTerms() {
        return [
            this.createPageBreak(),
            new Paragraph({
                text: 'ARTICLE V: ANNUAL RE-PETITION',
                heading: HeadingLevel.HEADING_1,
                spacing: { before: 400, after: 200 }
            }),
            new Paragraph({
                text: 'Section 5.1 — Government Petition',
                heading: HeadingLevel.HEADING_2,
                spacing: { before: 200, after: 100 }
            }),
            new Paragraph({
                text: 'This acknowledgment shall be automatically re-submitted annually to relevant government entities following the Belinda Sutton precedent (1783).',
                spacing: { after: 200 }
            })
        ];
    }

    /**
     * Create exhibits section with primary sources
     * ENHANCED: Now includes detailed Exhibits A-E matching template structure
     */
    createExhibits(slaveholderData) {
        const sections = [
            this.createPageBreak(),
            new Paragraph({
                text: 'EXHIBITS',
                heading: HeadingLevel.HEADING_1,
                alignment: AlignmentType.CENTER,
                spacing: { before: 400, after: 400 }
            })
        ];

        // Exhibit A: Primary Source Documents (per slaveholder)
        sections.push(...this.createExhibitA(slaveholderData));
        
        // Exhibit B: Calculation Methodology
        sections.push(...this.createExhibitB());
        
        // Exhibit C: Schedule of Enslaved Persons
        sections.push(...this.createExhibitC(slaveholderData));
        
        // Exhibit D: Step-by-Step Inheritance Accounting
        sections.push(...this.createExhibitD(slaveholderData));
        
        // Exhibit E: Summary of Debts
        sections.push(...this.createExhibitE(slaveholderData));

        return sections;
    }
    
    /**
     * EXHIBIT A: Primary Source Documents
     */
    createExhibitA(slaveholderData) {
        const sections = [];
        
        let exhibitLetter = 'A';
        for (const data of slaveholderData) {
            sections.push(
                this.createPageBreak(),
                new Paragraph({
                    text: `EXHIBIT ${exhibitLetter}`,
                    heading: HeadingLevel.HEADING_1,
                    spacing: { before: 400, after: 200 }
                }),
                new Paragraph({
                    text: `PRIMARY SOURCE DOCUMENTATION`,
                    heading: HeadingLevel.HEADING_2,
                    alignment: AlignmentType.CENTER,
                    spacing: { after: 100 }
                }),
                new Paragraph({
                    text: data.slaveholder.slaveholder_name,
                    heading: HeadingLevel.HEADING_2,
                    alignment: AlignmentType.CENTER,
                    spacing: { after: 200 }
                })
            );

            // Citation information
            if (data.primarySources.length > 0) {
                const source = data.primarySources[0];
                sections.push(
                    new Paragraph({
                        text: 'Citation:',
                        bold: true,
                        spacing: { after: 50 }
                    }),
                    new Paragraph({
                        text: source.collection_name || 'Historical Records',
                        spacing: { after: 50 }
                    }),
                    new Paragraph({
                        text: `Document Type: ${source.document_type || 'Unknown'}`,
                        spacing: { after: 50 }
                    }),
                    new Paragraph({
                        text: `FamilySearch ARK: ${source.source_url || 'TBD'}`,
                        spacing: { after: 200 }
                    })
                );
                
                // TODO [JAN 2026]: Add full will text transcription
                sections.push(
                    new Paragraph({
                        text: '─'.repeat(70),
                        alignment: AlignmentType.CENTER,
                        spacing: { after: 100 }
                    }),
                    new Paragraph({
                        text: 'ORIGINAL DOCUMENT',
                        heading: HeadingLevel.HEADING_3,
                        alignment: AlignmentType.CENTER,
                        spacing: { after: 100 }
                    }),
                    new Paragraph({
                        text: `[Document accessible at: ${source.s3_url || 'S3 URL'}]`,
                        italics: true,
                        alignment: AlignmentType.CENTER,
                        spacing: { after: 100 }
                    }),
                    new Paragraph({
                        text: 'TODO [JAN 2026]: Extract and include full document text transcription here',
                        italics: true,
                        spacing: { after: 200 }
                    })
                );
            }

            // List enslaved persons documented in this source
            sections.push(
                new Paragraph({
                    text: 'Enslaved Persons Documented:',
                    bold: true,
                    spacing: { before: 200, after: 100 }
                })
            );

            for (const person of data.enslavedPersons) {
                sections.push(
                    new Paragraph({
                        text: `• ${person.enslaved_name}${person.gender ? ` (${person.gender})` : ''}`,
                        spacing: { after: 50 }
                    })
                );
            }

            exhibitLetter = String.fromCharCode(exhibitLetter.charCodeAt(0) + 1);
        }

        return sections;
    }
    
    /**
     * EXHIBIT B: Calculation Methodology
     * TODO [JAN 2026]: Verify economic methodology with research team
     */
    createExhibitB() {
        return [
            this.createPageBreak(),
            new Paragraph({
                text: 'EXHIBIT B',
                heading: HeadingLevel.HEADING_1,
                spacing: { before: 400, after: 200 }
            }),
            new Paragraph({
                text: 'CALCULATION METHODOLOGY',
                heading: HeadingLevel.HEADING_2,
                alignment: AlignmentType.CENTER,
                spacing: { after: 200 }
            }),
            new Paragraph({
                text: 'B-1: Base Debt Per Person-Year',
                heading: HeadingLevel.HEADING_3,
                spacing: { before: 200, after: 100 }
            }),
            new Paragraph({
                text: 'The base debt calculation incorporates three components:',
                spacing: { after: 100 }
            }),
            new Paragraph({
                text: '1. Wage Theft: $36,000',
                spacing: { after: 50 }
            }),
            new Paragraph({
                text: '   Fair market wage for labor performed',
                spacing: { after: 50 }
            }),
            new Paragraph({
                text: '2. Dignity Damages: $22,500',
                spacing: { after: 50 }
            }),
            new Paragraph({
                text: '   Human rights violations and loss of freedom',
                spacing: { after: 50 }
            }),
            new Paragraph({
                text: '3. Profit Share: $120',
                spacing: { after: 50 }
            }),
            new Paragraph({
                text: '   Share of business proceeds generated by labor',
                spacing: { after: 100 }
            }),
            new Paragraph({
                text: 'Total Base Per Person-Year: $58,620',
                bold: true,
                spacing: { after: 200 }
            }),
            new Paragraph({
                text: 'TODO [JAN 2026]: Current system uses database formula. Verify $58,620 base with economic research.',
                italics: true,
                spacing: { after: 200 }
            }),
            new Paragraph({
                text: 'B-2: Compound Interest (4% Annual)',
                heading: HeadingLevel.HEADING_3,
                spacing: { before: 200, after: 100 }
            }),
            new Paragraph({
                text: 'Formula: Debt = Principal × (1 + r)ⁿ',
                spacing: { after: 50 }
            }),
            new Paragraph({
                text: 'Where:',
                spacing: { after: 50 }
            }),
            new Paragraph({
                text: '  r = 0.04 (4% annual rate)',
                spacing: { after: 50 }
            }),
            new Paragraph({
                text: '  n = years from end of ownership to 2025',
                spacing: { after: 100 }
            }),
            new Paragraph({
                text: 'Example: For ownership ending in 1862 (n = 163 years):',
                spacing: { after: 50 }
            }),
            new Paragraph({
                text: '  Multiplier = (1.04)¹⁶³ = 596.63',
                spacing: { after: 200 }
            }),
            new Paragraph({
                text: 'B-3: Delayed Justice Penalty',
                heading: HeadingLevel.HEADING_3,
                spacing: { before: 200, after: 100 }
            }),
            new Paragraph({
                text: 'Additional penalty for 160 years since 1865 Emancipation:',
                spacing: { after: 50 }
            }),
            new Paragraph({
                text: 'Delayed Justice = (Principal + Interest) × 0.02 × 160',
                spacing: { after: 50 }
            }),
            new Paragraph({
                text: 'Delayed Justice = (Principal + Interest) × 3.2',
                spacing: { after: 100 }
            }),
            new Paragraph({
                text: 'This accounts for the failure of the government to provide restitution within a reasonable timeframe.',
                spacing: { after: 200 }
            })
        ];
    }
    
    /**
     * EXHIBIT C: Schedule of Enslaved Persons
     * TODO [JAN 2026]: Add birth year estimation logic
     */
    createExhibitC(slaveholderData) {
        const sections = [
            this.createPageBreak(),
            new Paragraph({
                text: 'EXHIBIT C',
                heading: HeadingLevel.HEADING_1,
                spacing: { before: 400, after: 200 }
            }),
            new Paragraph({
                text: 'SCHEDULE OF ENSLAVED PERSONS',
                heading: HeadingLevel.HEADING_2,
                alignment: AlignmentType.CENTER,
                spacing: { after: 200 }
            })
        ];
        
        // Create table for all enslaved persons
        const tableRows = [
            new TableRow({
                children: [
                    new TableCell({ children: [new Paragraph({ text: 'Name', bold: true })] }),
                    new TableCell({ children: [new Paragraph({ text: 'Est. Birth Year', bold: true })] }),
                    new TableCell({ children: [new Paragraph({ text: 'Relationship', bold: true })] }),
                    new TableCell({ children: [new Paragraph({ text: 'Years Enslaved', bold: true })] })
                ]
            })
        ];
        
        // Add row for each enslaved person
        for (const data of slaveholderData) {
            for (const person of data.enslavedPersons) {
                // TODO [JAN 2026]: Implement birth year estimation
                const birthYear = person.birth_year || 'Unknown';
                const relationship = person.relationship_type || '-';
                const years = person.years_enslaved || 30; // Default 30 if unknown
                
                tableRows.push(
                    new TableRow({
                        children: [
                            new TableCell({ children: [new Paragraph(person.enslaved_name)] }),
                            new TableCell({ children: [new Paragraph(birthYear.toString())] }),
                            new TableCell({ children: [new Paragraph(relationship)] }),
                            new TableCell({ children: [new Paragraph(years.toString())] })
                        ]
                    })
                );
            }
        }
        
        sections.push(
            new Table({
                width: { size: 100, type: WidthType.PERCENTAGE },
                rows: tableRows
            }),
            new Paragraph({
                text: '',
                spacing: { after: 200 }
            }),
            new Paragraph({
                text: 'TODO [JAN 2026]: Enhance birth year estimation using FamilySearch data and historical context.',
                italics: true,
                spacing: { after: 100 }
            })
        );
        
        return sections;
    }
    
    /**
     * EXHIBIT D: Step-by-Step Inheritance Accounting
     * TODO [JAN 2026]: Add multi-generation ownership chain calculations
     */
    createExhibitD(slaveholderData) {
        const sections = [
            this.createPageBreak(),
            new Paragraph({
                text: 'EXHIBIT D',
                heading: HeadingLevel.HEADING_1,
                spacing: { before: 400, after: 200 }
            }),
            new Paragraph({
                text: 'STEP-BY-STEP INHERITANCE ACCOUNTING',
                heading: HeadingLevel.HEADING_2,
                alignment: AlignmentType.CENTER,
                spacing: { after: 200 }
            })
        ];
        
        // Per-person calculation blocks
        for (const data of slaveholderData) {
            for (const person of data.enslavedPersons) {
                sections.push(
                    new Paragraph({
                        text: '═'.repeat(70),
                        spacing: { before: 200, after: 100 }
                    }),
                    new Paragraph({
                        text: person.enslaved_name.toUpperCase(),
                        bold: true,
                        spacing: { after: 50 }
                    }),
                    new Paragraph({
                        text: `Enslaved by: ${data.slaveholder.slaveholder_name}`,
                        spacing: { after: 100 }
                    })
                );
                
                // TODO [JAN 2026]: Multi-generation calculation
                const years = person.years_enslaved || 30;
                const baseDebt = years * 58620; // Using template's $58,620 per year
                const withInterest = baseDebt * 596.63; // Simplified 4% compound
                const withPenalty = withInterest * 3.2; // Delayed justice
                
                sections.push(
                    new Paragraph({
                        text: `Years Enslaved: ${years}`,
                        spacing: { after: 50 }
                    }),
                    new Paragraph({
                        text: `Base Debt: $${baseDebt.toLocaleString()}`,
                        spacing: { after: 50 }
                    }),
                    new Paragraph({
                        text: `With Compound Interest (4%, ~163 years): $${withInterest.toLocaleString('en-US', { maximumFractionDigits: 0 })}`,
                        spacing: { after: 50 }
                    }),
                    new Paragraph({
                        text: `With Delayed Justice Penalty (3.2x): $${withPenalty.toLocaleString('en-US', { maximumFractionDigits: 0 })}`,
                        spacing: { after: 100 }
                    }),
                    new Paragraph({
                        text: `TOTAL DEBT FOR ${person.enslaved_name.toUpperCase()}: $${withPenalty.toLocaleString('en-US', { maximumFractionDigits: 0 })}`,
                        bold: true,
                        spacing: { after: 100 }
                    })
                );
            }
        }
        
        sections.push(
            new Paragraph({
                text: '═'.repeat(70),
                spacing: { before: 200, after: 200 }
            }),
            new Paragraph({
                text: 'TODO [JAN 2026]: Add multi-generation ownership calculations (e.g., Hopewell → Biscoe chains).',
                italics: true,
                spacing: { after: 100 }
            })
        );
        
        return sections;
    }
    
    /**
     * EXHIBIT E: Summary of Debts
     */
    createExhibitE(slaveholderData) {
        const sections = [
            this.createPageBreak(),
            new Paragraph({
                text: 'EXHIBIT E',
                heading: HeadingLevel.HEADING_1,
                spacing: { before: 400, after: 200 }
            }),
            new Paragraph({
                text: 'SUMMARY OF DEBTS',
                heading: HeadingLevel.HEADING_2,
                alignment: AlignmentType.CENTER,
                spacing: { after: 200 }
            })
        ];
        
        // Create summary table
        const tableRows = [
            new TableRow({
                children: [
                    new TableCell({ children: [new Paragraph({ text: 'Enslaved Person', bold: true })] }),
                    new TableCell({ children: [new Paragraph({ text: 'Slaveholder', bold: true })] }),
                    new TableCell({ children: [new Paragraph({ text: 'Debt Amount', bold: true })] })
                ]
            })
        ];
        
        let grandTotal = 0;
        
        for (const data of slaveholderData) {
            for (const person of data.enslavedPersons) {
                const years = person.years_enslaved || 30;
                const debt = years * 58620 * 596.63 * 3.2; // Simplified calculation
                grandTotal += debt;
                
                tableRows.push(
                    new TableRow({
                        children: [
                            new TableCell({ children: [new Paragraph(person.enslaved_name)] }),
                            new TableCell({ children: [new Paragraph(data.slaveholder.slaveholder_name)] }),
                            new TableCell({ children: [new Paragraph(`$${debt.toLocaleString('en-US', { maximumFractionDigits: 0 })}`)] })
                        ]
                    })
                );
            }
        }
        
        // Grand total row
        tableRows.push(
            new TableRow({
                children: [
                    new TableCell({ children: [new Paragraph({ text: 'GRAND TOTAL', bold: true })] }),
                    new TableCell({ children: [new Paragraph('')] }),
                    new TableCell({ children: [new Paragraph({ text: `$${grandTotal.toLocaleString('en-US', { maximumFractionDigits: 0 })}`, bold: true })] })
                ]
            })
        );
        
        sections.push(
            new Table({
                width: { size: 100, type: WidthType.PERCENTAGE },
                rows: tableRows
            }),
            new Paragraph({
                text: '',
                spacing: { after: 200 }
            }),
            new Paragraph({
                text: '─'.repeat(70),
                alignment: AlignmentType.CENTER,
                spacing: { after: 100 }
            }),
            new Paragraph({
                text: `TOTAL DEBT (Direct Line): $${grandTotal.toLocaleString('en-US', { maximumFractionDigits: 0 })}`,
                bold: true,
                alignment: AlignmentType.CENTER,
                spacing: { after: 100 }
            }),
            new Paragraph({
                text: '─'.repeat(70),
                alignment: AlignmentType.CENTER,
                spacing: { after: 200 }
            }),
            new Paragraph({
                text: 'Note: This total reflects the documented enslaved persons in Obligor\'s direct ancestral line. Per stirpes division among all descendants will be calculated upon execution of similar acknowledgments by other family members.',
                italics: true,
                spacing: { after: 100 }
            })
        );
        
        return sections;
    }

    /**
     * Create signature page
     */
    createSignaturePage(acknowledgerInfo, daaRecord) {
        return [
            this.createPageBreak(),
            new Paragraph({
                text: 'EXECUTION',
                heading: HeadingLevel.HEADING_1,
                alignment: AlignmentType.CENTER,
                spacing: { before: 400, after: 400 }
            }),
            new Paragraph({
                text: 'IN WITNESS WHEREOF, the undersigned Obligor acknowledges the foregoing debt calculations based on the primary source documentation and executes this Agreement.',
                spacing: { after: 400 }
            }),
            new Paragraph({
                text: 'OBLIGOR:',
                spacing: { before: 200, after: 100 }
            }),
            new Paragraph({
                text: '________________________________________',
                spacing: { after: 50 }
            }),
            new Paragraph({
                text: acknowledgerInfo.name.toUpperCase(),
                spacing: { after: 100 }
            }),
            new Paragraph({
                text: 'Date: ____________________',
                spacing: { after: 400 }
            }),
            new Paragraph({
                text: '— END OF AGREEMENT —',
                alignment: AlignmentType.CENTER,
                spacing: { before: 400 }
            }),
            new Paragraph({
                text: `Document No. ${daaRecord.agreementNumber} | Reparations ∈ ℝ`,
                alignment: AlignmentType.CENTER,
                spacing: { after: 200 }
            })
        ];
    }

    /**
     * Create page break
     */
    createPageBreak() {
        return new Paragraph({
            text: '',
            pageBreakBefore: true
        });
    }
}

module.exports = DAADocumentGenerator;
