-- Migration 062: notes-provenance + external-id evidence methodologies
-- Date: 2026-04-29
--
-- Per memory-bank/plan-apr29-will-source-registry-dual-ledger-daa.md §7
-- Stage 2.5 (investigation follow-up). The Stage 2 bootstrap left 128,001
-- canonical_persons with person_type='enslaver' but no compendium row.
-- Investigation showed all 128,001 carry primary-source citations in their
-- notes column, populated by past bulk-import scripts that never wrote
-- structured evidence rows. This migration registers the methodologies
-- under which Stage 2.5 extracts those citations into M053.
--
-- The notes-parse methodology is admittedly fragile (regex on free-text)
-- but the citations themselves are deterministic — every row in a given
-- pattern was written by the same import script with a consistent prefix.
-- Misclassification risk is low for this specific corpus; future bulk
-- imports should write structured M053 rows directly.

INSERT INTO estimation_methodology_registry (name, version, description, role_tags, assumptions_jsonb, citations, known_failure_modes) VALUES ('canonical_persons_notes_provenance_parser', '1.0.0', 'Stage 2.5 backfill methodology: parse canonical_persons.notes for structured primary-source citations written by past bulk-import scripts (SlaveVoyages roles, Louisiana Slave Database transactions, 1860 Slave Schedule promotions, Santos Brazil enslaved census, civilwardc.org DC compensation petitions, Natchez probate records, Maryland State Archives SC 2908 Vol. 812, etc.). Each match emits one compendium row with the matched citation in claim_summary and evidence_source_table set to the canonical source identifier. Tier per source: most direct primary attestations are Tier A; ship_captain roles (where ownership of cargo is not legally established) are Tier B.', ARRAY['legacy_source_acknowledgment','provenance_extraction','evidence_strength'], '{"approach": "deterministic_pattern_match_on_notes_prefix", "source_to_tier_mapping": {"slavevoyages_transatlantic_ship_owner": "A", "slavevoyages_transatlantic_ship_captain": "B", "slavevoyages_intraamerican_ship_owner": "A", "slavevoyages_intraamerican_ship_captain": "B", "louisiana_slave_db_import": "A", "louisiana_slave_db_transactions": "A", "census_1860_slave_schedule_ocr": "A", "santos_brazil_enslaved_census": "A", "civilwardc_petitions_direct": "A", "natchez_probate_records": "A", "mdsa_sc2908_vol812": "A"}}'::jsonb, 'Internal project: bulk-import scripts dating to 2025-12 through 2026-04 that wrote provenance to canonical_persons.notes rather than structured evidence rows. Stage 2.5 investigation documented in memory-bank/plan-apr29-will-source-registry-dual-ledger-daa.md.', 'Pattern matching is fragile to bulk-import prefix changes. Citation in notes does not guarantee verification of the underlying primary source. Going-forward imports must write structured M053 rows directly rather than relying on notes-parse backfill.') ON CONFLICT (name, version) DO NOTHING;

INSERT INTO estimation_methodology_registry (name, version, description, role_tags, assumptions_jsonb, citations, known_failure_modes) VALUES ('person_external_ids_pointer', '1.0.0', 'Acknowledgment of person_external_ids linkages as Tier B (indirect_primary) evidence for canonical_persons classification. A canonical_person with a verified FamilySearch ID (or other genealogy database external id) carries documentary support that they are a real person with a verifiable external profile, but the external profile may not directly attest enslaver status — the linkage is supportive rather than direct.', ARRAY['legacy_source_acknowledgment','evidence_strength'], '{"source_table": "person_external_ids", "tier": "B", "supports_existence": true, "directly_attests_enslaver_status": false}'::jsonb, 'Internal project: person_external_ids stores FamilySearch IDs and other external genealogy database identifiers per canonical_person.', 'A FamilySearch profile existing for a person does not by itself attest enslaver status; the profile may or may not contain enslavement-relevant content. Reviewer should examine specific profiles for direct content.') ON CONFLICT (name, version) DO NOTHING;
