import 'dotenv/config'; import pg from 'pg';
const p=new pg.Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false}});
const q='Israel Kniffen Fishkill Dutchess estate Negro Man Jack Marry';
const er=await fetch((process.env.OLLAMA_URL||'http://127.0.0.1:11434/api/embeddings'),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({model:'nomic-embed-text',prompt:q})});
const qv='['+(await er.json()).embedding.join(',')+']';
const kid=(await p.query("SELECT id FROM person_documents WHERE ocr_text ILIKE '%Israel Kniffen%' AND length(ocr_text)>800 LIMIT 1")).rows[0].id;
const nc=(await p.query("SELECT count(*)::int n FROM embeddings WHERE subject_id=$1 AND content_kind='doc_ocr' AND chunk_index>0",[String(kid)])).rows[0].n;
const best=(await p.query("SELECT chunk_index,1-(embedding<=>$1::vector) sim FROM embeddings WHERE subject_id=$2 AND content_kind='doc_ocr' ORDER BY embedding<=>$1::vector LIMIT 1",[qv,String(kid)])).rows[0];
const top=(await p.query("SELECT DISTINCT subject_id FROM (SELECT subject_id,embedding<=>$1::vector d FROM embeddings WHERE content_kind='doc_ocr' AND model='nomic-embed-text' ORDER BY d LIMIT 30) x",[qv])).rows.map(r=>r.subject_id);
console.log('KNITEST doc#'+kid+' chunks='+nc+' best_sim='+(best?(+best.sim).toFixed(3)+'(ci'+best.chunk_index+')':'-')+' in_top8='+(top.slice(0,8).includes(String(kid))?'YES':'no rank'+(top.indexOf(String(kid))+1||'>30')));
await p.end();
